services:
  - docker

before_install:
  - docker build -t robertbeal/homeassistant .
  - docker run -d --name=homeassistant --health-cmd="curl --fail http://127.0.0.1:8123/api || exit 1" --health-interval=5s --health-retries=3 robertbeal/homeassistant

script:
  - sleep 30
  - if [[ -z 'docker ps --filter="name=homeassistant" --filter="health=healthy" -q' ]]; then exit 1; fi
